server:
  port: 8080
spring:
#  数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.246.116:3306/wechatbot?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: diaosiNANREN1234
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
#      JSP目录
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
#      mybatis配置
mybatis:
  type-aliases-package: com.wechat.bot.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
