server:
  port: 8080
spring:
#  数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://local.mysql.com:3306/ddd?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: dddd
    password: dddd
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
#      JSP目录
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
#      mybatis配置
mybatis:
  type-aliases-package: com.wechat.bot.entity
  mapper-locations: classpath:/mappers/*
  configuration:
    mapUnderscoreToCamelCase: true